routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware(['roles:1,2']);


/**
 * ROUTES FOR VACATIONS
 */
Route::resource('vacations', 'VacationController')->middleware(['roles:1,2']);
Route::get('vacation/{id}/approve', 'VacationController@approve')->name('vacation-approve')->middleware(['roles:1']);
Route::get('vacation/{id}/reject', 'VacationController@reject')->name('vacation-reject')->middleware(['roles:1']);

/**
 * ROUTES FOR PAYROLLES
 */
Route::resource('payrolls', 'PayrollController')->middleware(['roles:1,2']);

app/Vacation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Vacation extends Model
{
    use SoftDeletes;

    protected $table = "vacations";
    protected $dates = ['deleted_at'];

    public function user(){
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/VacationController.php
<?php

namespace App\Http\Controllers;

use App\Vacation;
use App\User;
use App\Collection;
use App\Http\Requests\StoreVacation;
use App\Http\Requests\UpdateVacation;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class VacationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Auth::user()->role_id == 1){
            $data['vacations'] = Vacation::all();    
        }else{
            $data['vacations'] = Vacation::where('user_id', Auth::user()->id)->get();
        }
        return view('Vacation.list', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['route'] = route('vacations.store');
        $data['method'] = 'POST';
        $data['mode'] = 'New';
        return view('Vacation.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\StoreVacation  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreVacation $request)
    {
        $vacation = new Vacation();

        $vacation->start_date = $request->start_date;
        $vacation->end_date = $request->end_date;
        $vacation->days = $request->days;
        $vacation->reason = $request->reason;
        $vacation->user_id = Auth::user()->id;
        $vacation->status = 'PENDING';

        $vacation->save();
        
        $data['flush'] = 'Vacation request created successfully';
        return redirect()->route('vacations.index')->with($data);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Vacation  $vacation
     * @return \Illuminate\Http\Response
     */
    public function show(Vacation $vacation)
    {
        $data['vacation'] = $vacation;
        return view('Vacation.page', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Vacation  $vacation
     * @return \Illuminate\Http\Response
     */
    public function edit(Vacation $vacation)
    {
        if($vacation->user_id != Auth::user()->id){
            abort(403, 'You are not authorized to access this page, please check system admin.');
        }

        $data['vacation'] = $vacation;
        $data['route'] = route('vacations.update', ['vacations' => $vacation->id]);
        $data['method'] = 'PUT';
        $data['mode'] = 'Update';
        return view('Vacation.form', $data);
    }

     /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\UpdateVacation  $request
     * @param  \App\Vacation  $vacation
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateVacation $request, Vacation $vacation)
    {
        if($vacation->user_id != Auth::user()->id){
            abort(403, 'You are not authorized to access this page, please check system admin.');
        }

        $vacation->start_date = $request->start_date;
        $vacation->end_date = $request->end_date;
        $vacation->days = $request->days;
        $vacation->reason = $request->reason;

        $vacation->save();
        
        $data['flush'] = 'Vacation updated successfully';
        return redirect()->route('vacations.index')->with($data);
    }

    /**
     * Approve specified vacation.
     *
     * @param  $id
     * @return \Illuminate\Http\Response
     */
    public function approve($id)
    {
        $vacation = Vacation::find($id);
        
        $vacation->status = 'APPROVED';

        $vacation->save();

        $user = User::find($vacation->user_id);
        $user->vacations_balance--;

        $user->save();
        
        $data['flush'] = 'Vacation approved successfully';
        return redirect()->route('vacations.index')->with($data);
    }

    /**
     * Reject specified vacation.
     *
     * @param  $id
     * @return \Illuminate\Http\Response
     */
    public function reject($id)
    {
        $vacation = Vacation::find($id);
        
        if($vacation->status == 'APPROVED'){
            $user = User::find($vacation->user_id);
            $user->vacations_balance++;
            $user->save();
        }

        $vacation->status = 'REJECTED';

        $vacation->save();


        
        $data['flush'] = 'Vacation rejected successfully';
        return redirect()->route('vacations.index')->with($data);
    }

   

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Vacation  $vacation
     * @return \Illuminate\Http\Response
     */
    public function destroy(Vacation $vacation)
    {
        if($vacation->user_id != Auth::user()->id){
            abort(403, 'You are not authorized to access this page, please check system admin.');
        }
        $vacation->destroy($vacation->id);
        $url = route('vacations.index');
        return $url;
    }
}

resources/views/Vacation/form.blade.php
@extends('layouts.egy')

@section('title')
Vacations Managment
@endsection

@section('style')
<!-- BEGIN PAGE LEVEL PLUGINS -->
<link href="{{ url('/public') }}/assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css" rel="stylesheet" type="text/css" />
<!-- END PAGE LEVEL PLUGINS -->
@endsection

@section('script')
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="{{ url('/public') }}/assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
{{-- Custom Script --}}
<script type="text/javascript">
    $('.date-picker').datepicker({
        atutoclose : true,
        format : 'yyyy-mm-dd',
    });

    $(document).ready(function(){
        var start_date;
        var end_date;
        var days;

        $('#start_date').change(function(){
            start_date = new Date($('#start_date').val());
            end_date = new Date($('#end_date').val());
            days = (end_date.getTime() - start_date.getTime())/ (1000 * 3600 * 24);
            $('#days').val(days)
        });

        $('#end_date').change(function(){
            start_date = new Date($('#start_date').val());
            end_date = new Date($('#end_date').val());
            days = (end_date.getTime() - start_date.getTime())/ (1000 * 3600 * 24);
            $('#days').val(days)
        });
    });
</script>
@endsection

@section('content')
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption font-green">
                    <i class="icon-pin font-green"></i>
                    <span class="caption-subject bold uppercase"> {{$mode}} Vacation</span>
                </div>
            </div>
            <div class="portlet-body form">
            <form role="form" action="{{$route}}" method="POST">
                @method($method)
                @csrf
                <div class="form-body">
                    <div class="form-group form-md-line-input form-md-floating-label @error('start_date') has-error @enderror">
                        <input class="form-control date-picker" size="16" type="text" name="start_date" id="start_date" value="{{old('start_date', isset($vacation->start_date) ? date('Y-m-d', strtotime($vacation->start_date)) : null)}}" />
                        <label for="form_control_1">Start date @error('start_date') {{$message}} @enderror</label>
                        <span class="help-block"> Select start date of vacation </span>
                    </div>

                    <div class="form-group form-md-line-input form-md-floating-label @error('end_date') has-error @enderror">
                        <input class="form-control date-picker" size="16" type="text" name="end_date" id="end_date" value="{{old('end_date', isset($vacation->end_date) ? date('Y-m-d', strtotime($vacation->end_date)) : null)}}" />
                        <label for="form_control_1">End date @error('end_date') {{$message}} @enderror</label>
                        <span class="help-block"> Select end date of vacation </span>
                    </div>

                    <div class="form-group form-md-line-input form-md-floating-label @error('days') has-error @enderror">
                        <input type="number" name="days" id="days" value="{{old('days', isset($vacation->days) ? $vacation->days : null)}}" class="form-control" readonly>
                        <label for="form_control_1">@error('days') {{$message}} @enderror</label>
                        <span class="help">This is no of days requested for vacation</span>
                    </div>

                    <div class="form-group form-md-line-input form-md-floating-label @error('reason') has-error @enderror">
                        <textarea name="reason" class="form-control" rows="10">{{old('reason', isset($vacation->reason) ? $vacation->reason : null)}}</textarea>
                        <label for="form_control_1">Vacation reason @error('reason') {{$message}} @enderror</label>
                    </div>

                    <div class="form-actions noborder">
                        <button type="submit" class="btn blue">Submit</button>
                        <button type="reset" class="btn default">Cancel</button>
                    </div>
                </div>
            </form>
            </div>
        </div>
        <!-- END SAMPLE FORM PORTLET-->
    </div>
</div>
@endsection

resources/views/Vacation/list.blade.php
@extends('layouts.egy')

@section('title')
Vacations Managment
@endsection

@section('style')
<!-- BEGIN PAGE LEVEL PLUGINS -->
<link href="{{ url('/public') }}/assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="{{ url('/public') }}/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<!-- END PAGE LEVEL PLUGINS -->
{{-- custom style --}}
<style>
    .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th {
        vertical-align : middle;
        text-align : center;
    }
    .table>tbody>tr>td img {
        width : 180px;
    }
    .default{
        color : #fff;
    }
    .primary{
        color : #337ab7;
    }
    .success{
        color : #36c6d3;
    }
    .lable-APPROVED{
        background-color: #36c6d3;
    }
    .info{
        color : #659be0;
    }
    .warning{
        color : #F1C40F;
    }
    .lable-PENDING{
        background-color: #F1C40F;
    }
    .danger{
        color : #ed6b75;
    }
    .lable-REJECTED{
        background-color: #ed6b75;
    }
</style>
@endsection

@section('script')
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="{{ url('/public') }}/assets/global/scripts/datatable.js" type="text/javascript"></script>
<script src="{{ url('/public') }}/assets/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="{{ url('/public') }}/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{{ url('/public') }}/assets/pages/scripts/table-datatables-managed.min.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
{{-- Custom script --}}
<script>
    var baseurl = '{{url('/')}}';
    $(document).ready(function(){
        $(".removeItem").click(function(e) {
            var id = $(this).data('id');
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                },
                buttonsStyling: false
            })

            swalWithBootstrapButtons.fire({
            title: 'Are you sure?',
            text: "You won't be able to delete this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'No, cancel!',
            reverseButtons: true
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        url: baseurl+'/vacations/'+id,
                        type: 'DELETE',  // user.destroy
                        data: {
                            "_token": "{{ csrf_token() }}",
                        },
                        success: function(result) {
                            swalWithBootstrapButtons.fire(
                                'Deleted!',
                                'Vacation request has been deleted.',
                                'success'
                            )
                            window.location.replace(result);

                        }
                    });
                } else if (
                    /* Read more about handling dismissals below */
                    result.dismiss === Swal.DismissReason.cancel
                ) {
                    swalWithBootstrapButtons.fire(
                    'Cancelled',
                    'Your imaginary file is safe :)',
                    'error'
                    )
                }
            })
        });
    });
</script>
@endsection

@section('content')
@if(session('flush'))
<div class="alert alert-success"> {{session('flush')}} </div>
@endif
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption font-dark">
                    <i class="icon-settings font-dark"></i>
                    <span class="caption-subject bold uppercase"> 
                        @if(Auth::user()->role_id == 2) 
                            Your Vacations Balance {{Auth::user()->vacations_balance}} Days
                        @elseif(Auth::user()->role_id == 1) 
                            Vacations List 
                        @endif
                    </span>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-toolbar">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="btn-group">
                                <a href="{{route('vacations.create')}}">
                                    <button id="sample_editable_1_new" class="btn sbold green"> Add New
                                        <i class="fa fa-plus"></i>
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <table class="table table-striped table-bordered table-hover table-checkable order-column" id="sample_1">
                    <thead>
                        <tr>
                            <th> From </th>
                            <th> TO </th>
                            <th> Days </th>
                            <th> Reason </th>
                            <th> Status </th>
                            <th> Actions </th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(!empty($vacations))
                        @foreach ($vacations as $vacation)
                        <tr class="odd gradeX">
                            <td>
                                {{$vacation->start_date}}
                            </td>
                            <td>
                                {{$vacation->end_date}}
                            </td>
                            <td>
                                {{$vacation->days}}
                            </td>
                            <td>
                                {{$vacation->reason}}
                            </td>
                            <td>
                                <span class="label label-sm lable-{{$vacation->status}}"> {{$vacation->status}} </span>
                            </td>
                            <td>
                                <a href="{{route('vacations.show', $vacation)}}"><i class="icon-eye info"></i></a>
                                @if(Auth::user()->role_id == 2 && $vacation->user_id == Auth::user()->id)
                                    |
                                <a href="{{route('vacations.edit', $vacation)}}"><i class="icon-note success"></i></a> 
                                    | 
                                <a href="javascript:;" class="removeItem" data-id="{{$vacation->id}}"><i class="icon-trash danger"></i> </a>
                                @endif
                            </td>
                        </tr>
                        @endforeach
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>
@endsection

resources/views/Vacation/page.blade.php
@extends('layouts.egy')

@section('title')
Vacations Managment
@endsection

@section('style')
<!-- BEGIN PAGE LEVEL PLUGINS -->
<link href="{{ url('/public') }}/assets/pages/css/blog.min.css" rel="stylesheet" type="text/css" />
<!-- END PAGE LEVEL PLUGINS -->
@endsection

@section('script')

@endsection

@section('content')
<div class="blog-page blog-content-2">
    <div class="row">
        <div class="col-lg-12">
            <div class="blog-single-content bordered blog-container">
                
                <div class="blog-single-desc">
                    <p>Dear Manager </p>
                    <br>
                    <p> kindly Approved for my vacation request from {{$vacation->start_date}} to {{$vacation->end_date}} within {{$vacation->days}} days for {{$vacation->reason}}</p>
                    <br>
                    <p>Thank you</p>
                    <br>
                    <p>{{$vacation->user->firstname}} {{$vacation->user->lastname}}</p>
                </div>

                @if(Auth::user()->role_id == 1)
                @if($vacation->status == 'PENDING' || $vacation->status == 'REJECTED')
                <div class="form-group">
                    <a href="{{route('vacation-approve', $vacation->id)}}" class="btn green uppercase btn-md sbold btn-block">Approve
                        <i class="fa fa-check"></i>
                    </a>
                </div>
                @endif
                @if($vacation->status == 'PENDING' || $vacation->status == 'APPROVED')
                <div class="form-group">
                    <a href="{{route('vacation-reject', $vacation->id)}}" class="btn red uppercase btn-md sbold btn-block">Reject
                        <i class="fa fa-close"></i>
                    </a>
                </div>
                @endif
                @endif
            </div>
        </div>
    </div>
</div>
@endsection